#!/bin/bash

CHAPTERS="\
   01-preface.markdown \
   02-theory_of_fire.markdown \
   04-troubleshooting.markdown \
"

pandoc -S --epub-metadata=metadata.xml --epub-stylesheet=epub.css -o firebook.epub title.txt ${CHAPTERS}
pandoc -o firebook.pdf title.txt ${CHAPTERS}
