#!/bin/bash

CHAPTERS="\
   01-preface.markdown \
   02-theory_of_fire.markdown \
   04-troubleshooting.markdown \
"

pandoc -S --epub-metadata=metadata.xml --epub-stylesheet=epub.css --epub-cover-image=cover.jpg -o firebook.epub title.txt ${CHAPTERS}
pandoc -o firebook.pdf title.txt ${CHAPTERS}
kindlegen -o firebook.mobi firebook.epub
