default:
  font: Liberation Serif
  bold: "{* Bold}"
  mono: Liberation Mono
  prechap: "Chapter "
  postchap: ""
  presect: "Section "
  postsect: ""
  dql: "“"
  dqr: "”"
  con: "Contents"
  fig: "Figure "
  tab: "Table "
  indent: "\\qquad"
  thanks: "This is the PDF file for the Fire Book contents. It is licensed under the Creative Commons Attribution-Non Commercial-Share Alike 3.0 license."
ru:
  prechap: "Глава "
  presect: "Раздел "
  con: "Содержание"
  fig: "Рисунок "
  tab: "Таблица "
  dql: "«"
  dqr: "»"
